# 22/09/22


## Numpy


In [11]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype='int8')
print(arr)
print(arr.dtype)
#  print dimensions
print(arr.ndim)
# arr.shape
print(arr.shape)

print(arr.size)
print()


[[1 2 3]
 [4 5 6]]
int8
2
(2, 3)
6


In [17]:
arr1 = np.zeros((5), dtype='int32')
arr2 = np.zeros((5, 3))
print(arr1)
print(arr2)
arr3 = np.zeros((5, 2, 3))
print('\n')
print(arr3)


[0 0 0 0 0]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [30]:
print(np.ones((3, 3)))
arr = np.arange(15)
print(arr)

arr = arr.reshape((3, 5))
print(arr)
arr = np.arange(2, 17).reshape(3, 5)
print()
print(arr)
print()
arr = np.arange(2, 17, 2).reshape(4, 2)
print(arr)
print(arr*5)
print(arr**5)
print(arr-5)
print(arr+5)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[ 2  3  4  5  6]
 [ 7  8  9 10 11]
 [12 13 14 15 16]]

[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]
[[10 20]
 [30 40]
 [50 60]
 [70 80]]
[[     32    1024]
 [   7776   32768]
 [ 100000  248832]
 [ 537824 1048576]]
[[-3 -1]
 [ 1  3]
 [ 5  7]
 [ 9 11]]
[[ 7  9]
 [11 13]
 [15 17]
 [19 21]]


In [35]:
arr = np.arange(2, 17, 2).reshape(4, 2)*5
# print(arr)

print(arr > 20)

arr1 = np.array([[12, 14], [18, 25],
                 [42, 88], [55, 66]], dtype='int32')

print(arr*arr1)
print(arr < arr1)


[[False False]
 [ True  True]
 [ True  True]
 [ True  True]]
[[ 120  280]
 [ 540 1000]
 [2100 5280]
 [3850 5280]]
[[ True False]
 [False False]
 [False  True]
 [False False]]


# 23/09/22


In [4]:
import numpy as np

arr = np.array([[4, 5, 2], [6, 7, 2], [1, 0, 8]], dtype=np.int8)
arr.ndim
arr


array([[4, 5, 2],
       [6, 7, 2],
       [1, 0, 8]], dtype=int8)

In [5]:
print(arr.itemsize)


1


In [7]:
print(arr)
print('\n', arr.sum())


[[4 5 2]
 [6 7 2]
 [1 0 8]]

 35


In [8]:
print(arr.sum(axis=0))  # it is row wise, axis=1 is column wise


[11 12 12]


In [12]:
print(arr.sum(axis=1))
print(arr.min())
print(arr.min(axis=0))
print(arr.min(axis=1))


[11 15  9]
0
[1 0 2]
[2 2 0]


In [13]:
print(arr.mean())
print(arr.mean(axis=0))
print(arr.mean(axis=1))


3.888888888888889
[3.66666667 4.         4.        ]
[3.66666667 5.         3.        ]


In [15]:
print(arr.std())
print(arr.var())


2.6434171674156266
6.987654320987654


In [17]:
arr1 = np.array([[2, 6, 1], [5, 5, 6], [4, 5, 8]])
# matrix multiplication
print(arr.dot(arr1))
print('\n')
print(arr @ arr1)


[[41 59 50]
 [55 81 64]
 [34 46 65]]


[[41 59 50]
 [55 81 64]
 [34 46 65]]


In [20]:
print(arr)
print(np.sort(arr))  # default axis 1
print(np.sort(arr, axis=0))  # default axis 1
print()


[[4 5 2]
 [6 7 2]
 [1 0 8]]
[[2 4 5]
 [2 6 7]
 [0 1 8]]
[[1 0 2]
 [4 5 2]
 [6 7 8]]



In [23]:
print(np.insert(arr, 1, 0))


[4 0 5 2 6 7 2 1 0 8]


In [24]:
print(np.insert(arr, 1, [0, 0, 0]))


[4 0 0 0 5 2 6 7 2 1 0 8]


In [25]:
print(np.insert(arr, 1, [1, 1, 1], axis=0))


[[4 5 2]
 [1 1 1]
 [6 7 2]
 [1 0 8]]


In [26]:
print(np.insert(arr, 1, [1, 1, 1], axis=1))


[[4 1 5 2]
 [6 1 7 2]
 [1 1 0 8]]


In [27]:
print(np.append(arr, [1, 1, 1]))


[4 5 2 6 7 2 1 0 8 1 1 1]


In [28]:
print(np.append(arr, [1, 1, 1], axis=0))


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [29]:
print(np.append(arr, [[1, 1, 1]], axis=0))


[[4 5 2]
 [6 7 2]
 [1 0 8]
 [1 1 1]]


In [32]:
print(np.append(arr, [[1], [1], [1]], axis=1))


[[4 5 2 1]
 [6 7 2 1]
 [1 0 8 1]]


In [33]:
print(np.append(arr, [[1, 2], [1, 2], [1, 2]], axis=1))


[[4 5 2 1 2]
 [6 7 2 1 2]
 [1 0 8 1 2]]


In [41]:
#
print(np.append(arr, [arr1[0], arr1[1], arr1[2]], axis=1))


[[4 5 2 2 6 1]
 [6 7 2 5 5 6]
 [1 0 8 4 5 8]]


In [43]:
print(np.append(arr, [arr1.transpose()[0],
      arr1.transpose()[1], arr1.transpose()[2]], axis=1))


[[4 5 2 2 5 4]
 [6 7 2 6 5 5]
 [1 0 8 1 6 8]]


In [44]:
print(np.append(arr, [arr1[0], arr1[1], arr1[2]], axis=0))


[[4 5 2]
 [6 7 2]
 [1 0 8]
 [2 6 1]
 [5 5 6]
 [4 5 8]]


# 26/09/22


In [9]:
import numpy as np

In [5]:
arr = np.array([[2, 3, 5], [2, 6, 7], [8, 9, 1]])
arr1 = np.array([[5, 7, 5], [1, 6, 6], [9, 0, 2]])
print(arr)
print(arr1)


[[2 3 5]
 [2 6 7]
 [8 9 1]]
[[5 7 5]
 [1 6 6]
 [9 0 2]]


In [7]:
# merge
arr2 = np.concatenate((arr, arr1))
print(arr2)
arr2 = np.concatenate((arr, arr1), axis=1)
print(arr2)


[[2 3 5]
 [2 6 7]
 [8 9 1]
 [5 7 5]
 [1 6 6]
 [9 0 2]]
[[2 3 5 5 7 5]
 [2 6 7 1 6 6]
 [8 9 1 9 0 2]]


In [11]:
# random number arr
arr = np.random.rand(4, 3)  # values bw 0 and 1
print(arr)
arr = np.random.randint(10, 20, (4, 3))  # values bw 10 and 20
print(arr)


[[0.11848746 0.33293609 0.71880779]
 [0.07111922 0.4185765  0.37369739]
 [0.83466946 0.38796372 0.80047066]
 [0.79728669 0.83594798 0.53436226]]
[[17 10 15]
 [19 16 10]
 [11 17 13]
 [18 16 14]]


In [16]:
# multiply string with int
arr = np.array(['hello ', 'how ', 'r ', 'u '])
print(np.char.multiply(arr, 5))
# add strint to stirng arr
print(np.char.add(arr, '***'))


['hello hello hello hello hello ' 'how how how how how ' 'r r r r r '
 'u u u u u ']
['hello ***' 'how ***' 'r ***' 'u ***']


In [20]:
a = np.array([['hello', 'hey'], ['how', 'hi']])
c = np.array([[' how r u', ' welcome'], ['how r u', 'i am ur friend']])
b = np.random.randint(2, 10, (2, 2))
print(a)
print(b)


[['hello' 'hey']
 ['how' 'hi']]
[[7 7]
 [8 7]]


In [19]:
d = np.char.multiply(a, b)
print(d)


[['hellohellohellohellohellohellohellohello' 'heyheyheyheyhey']
 ['howhowhow' 'rrrr']]


In [21]:
d = np.char.add(a, c)
print(d)


[['hello how r u' 'hey welcome']
 ['howhow r u' 'hii am ur friend']]


In [23]:
arr = np.array([[1, 2, 5], [4, 6, 8], [6, 12, 78]])
print(arr)


[[ 1  2  5]
 [ 4  6  8]
 [ 6 12 78]]


In [28]:
print('ANY')
print(np.all(arr % 2 == 0))  # for whole arr
print(np.all(arr % 2 == 0, axis=0))  # for column
print(np.all(arr % 2 == 0, axis=1))  # for row

print('ALL')
print(np.any(arr % 2 == 0))  # for any one


ANY
False
[False  True False]
[False  True  True]
ALL
True


**Indexing and Slicing**


In [41]:
# indexing
print(arr)
print()
print(arr[0])
print(arr[0][2])
print(arr[0:2])  # 1st and 2nd row
print()
print(arr[:, 0])  # all row and 1st column

print(arr[1, 2])  # row index 1 index 2
print()
print(arr[1, :])
print()
print(arr[:, 0:2])
print()
print(arr[:, 1:])


[[ 1  2  5]
 [ 4  6  8]
 [ 6 12 78]]

[1 2 5]
5
[[1 2 5]
 [4 6 8]]

[1 4 6]
8

[4 6 8]

[[ 1  2]
 [ 4  6]
 [ 6 12]]

[[ 2  5]
 [ 6  8]
 [12 78]]


In [47]:
a = np.all(arr % 2 == 0, axis=0)
b = np.all(arr % 2 == 0, axis=1)


a = list(a)
print(a.index(True))


1


In [49]:
a = np.nonzero(arr % 2 == 0)
# array(row number), array(column number)


In [51]:
print(a[0])
print(a[1])

a = list(zip(a[0], a[1]))
print(a)


[0 1 1 1 2 2 2]
[1 0 1 2 0 1 2]
[(0, 1), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]


In [55]:
# and/or/not operation on np
# & | !

print((arr % 2 == 0) & (arr >= 10))


[[False False False]
 [False False False]
 [False  True  True]]


In [71]:
a = np.array([[5, 3, 6, 78, 3], [18, 12, 34, 12, 9], [
             56, 53, 52, 18, 7], [16, 17, 18, 20, 1], [1, 3, 6, 14, 1]])
print(a.shape)
print(a)


(5, 5)
[[ 5  3  6 78  3]
 [18 12 34 12  9]
 [56 53 52 18  7]
 [16 17 18 20  1]
 [ 1  3  6 14  1]]


In [64]:
b = np.nonzero((a % 2 == 0) & (a >= 10))

print(b)
# print(c)
b = list(zip(b[0], b[1]))
print(b)


(array([0, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4]), array([3, 0, 1, 2, 3, 0, 2, 3, 0, 2, 3, 4]))
[(0, 3), (1, 0), (1, 1), (1, 2), (1, 3), (2, 0), (2, 2), (2, 3), (3, 0), (3, 2), (3, 3), (4, 4)]


In [74]:
b = np.nonzero(np.all((a >= 10) & (a % 2 == 0), axis=0))
print(b[0])


[3]


# 27/09/22


In [2]:
import numpy as np

arr = np.array([[3, 2, 5], [6, 3, 2], [6, 4, 3]])
print(arr)
print(arr[:, [0]])
print(arr[:, 0:1])
print(arr[:, [0, 2]])


[[3 2 5]
 [6 3 2]
 [6 4 3]]
[[3]
 [6]
 [6]]
[[3]
 [6]
 [6]]
[[3 5]
 [6 2]
 [6 3]]


In [7]:
print(arr[[0, 0], [0, 2]])


[3 5]


In [11]:
temp = np.nonzero(arr % 2 == 0)
print(temp)
print(temp[0])
print(temp[1])


(array([0, 1, 1, 2, 2]), array([1, 0, 2, 0, 1]))
[0 1 1 2 2]
[1 0 2 0 1]


**Masking**


In [12]:
print(arr[temp[0], temp[1]])  # masking


[2 6 2 6 4]


In [13]:
temp = arr % 2 == 0
print(temp)


[[False  True False]
 [ True False  True]
 [ True  True False]]


In [14]:
arr[temp]


array([2, 6, 2, 6, 4])

In [30]:
arr = np.array([[2, 2, 54], [6, 3, 2], [6, 4, 6]])
print(arr)


[[ 2  2 54]
 [ 6  3  2]
 [ 6  4  6]]


In [31]:
temp = np.nonzero(np.all(arr % 2 == 0, axis=0))
print(temp[0])


[0 2]


In [35]:
print(arr[:, temp[0]])


[[ 2 54]
 [ 6  2]
 [ 6  6]]


In [37]:
temp = np.where(arr % 2 == 0)
print(temp)
l = list(zip(temp[0], temp[1]))
print(l)


(array([0, 0, 0, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 2, 0, 1, 2]))
[(0, 0), (0, 1), (0, 2), (1, 0), (1, 2), (2, 0), (2, 1), (2, 2)]


In [39]:
temp = np.where(arr % 2 == 0, True, False)  # cannot be done using nonzero()
print(temp)


[[ True  True  True]
 [ True False  True]
 [ True  True  True]]


In [40]:
arr = np.array([[3, 2, 5], [6, 3, 2], [6, 4, 3]])
print(np.where(arr % 2 == 0, [[4, 5, 4],
                              [4, 5, 4],
                              [4, 5, 4]], [[6, 2, 6],
                                           [6, 2, 6],
                                           [6, 2, 6]]))


[[6 5 6]
 [4 2 4]
 [4 5 6]]


In [45]:
arr = np.array([[2, 2, 4], [6, 3, 2], [6, 4, 6]])

# print(np.where(arr%2==0))
temp = np.where(np.all(arr % 2 == 0, axis=0))[0]
print(temp)
#  print 1 on where whole column is even
# np.where()


[0 2]


In [57]:
arr = np.array([[0, 2, 4], [0, 3, 2], [6, 4, 6]])
# clip function
print(arr >= 3)
# any value <1 will be set to one, any value >5 will become 5
print(np.clip(arr, 1, 5))


[[False False  True]
 [False  True False]
 [ True  True  True]]
[[1 2 4]
 [1 3 2]
 [5 4 5]]


In [63]:
arr = np.array([[2, 2, 0], [0, 3, 2], [6, 4, 6]])

row = np.where(arr % 2 == 0)[0]
column = np.where(arr % 2 == 0)[1]
print(list(zip(row, column)))


[(0, 0), (0, 1), (0, 2), (1, 0), (1, 2), (2, 0), (2, 1), (2, 2)]


In [64]:
a = np.argwhere(arr % 2 == 0)
print(a)


[[0 0]
 [0 1]
 [0 2]
 [1 0]
 [1 2]
 [2 0]
 [2 1]
 [2 2]]


In [70]:
import numpy as np
arr = np.array([[2, 2, 0, 4, 8], [6, 3, 2, 12, 16], [
               6, 4, 6, 14, 19], [9, 4, 14, 12, 22]])
col = np.where(np.all(arr % 2 == 0, axis=0))[0]
print(col)
arr[:, col] = np.clip(arr[:, col], 2, 10)
print(arr)


[2 3]
[[ 2  2  2  4  8]
 [ 6  3  2 10 16]
 [ 6  4  6 10 19]
 [ 9  4 10 10 22]]


In [78]:

arr = np.array([[2, 2, 0, 4, 8], [6, 3, 2, 12, 16], [
               6, 4, 6, 14, 19], [9, 4, 14, 12, 22]])
print(arr)
arr[:, np.where(np.all(arr % 2 == 0, axis=0))[0]] = np.clip(
    arr[:, np.where(np.all(arr % 2 == 0, axis=0))[0]], 2, 10)
print(arr)


[[ 2  2  0  4  8]
 [ 6  3  2 12 16]
 [ 6  4  6 14 19]
 [ 9  4 14 12 22]]
[[ 2  2  2  4  8]
 [ 6  3  2 10 16]
 [ 6  4  6 10 19]
 [ 9  4 10 10 22]]


In [10]:
# arr=nxn n is odd
# 

arr = np.array([[2, 2, 0, 4, 8], [6, 3, 2, 12, 16], [
               6, 4, 6, 14, 19], [9, 4, 14, 12, 22],[1,3,5,1,45]])
print(arr)

print(sum(arr[[i for i in range(len(arr[0]))],[i for i in range(len(arr))]]))
print(sum(arr[[i for i in range(len(arr[0]))],[i for i in range(len(arr)-1,-1,-1)]]))

[[ 2  2  0  4  8]
 [ 6  3  2 12 16]
 [ 6  4  6 14 19]
 [ 9  4 14 12 22]
 [ 1  3  5  1 45]]
68
31


In [3]:
for i in range(7):
    for j in range(7):
        print(f"{i}{j} ",end="")
    print()
arr=np.random.randint(0,49,(7,7))
print(arr)

00 01 02 03 04 05 06 
10 11 12 13 14 15 16 
20 21 22 23 24 25 26 
30 31 32 33 34 35 36 
40 41 42 43 44 45 46 
50 51 52 53 54 55 56 
60 61 62 63 64 65 66 
[[ 6 45 38  0  3 11 34]
 [ 0 35 29 21 21 32 31]
 [23  5  4 26 34 34 12]
 [20 35 24 12 24  7 21]
 [ 8  6 28  8  8 26  9]
 [46 48 26 23 35 18 39]
 [31 27 43 41 30 33 40]]


In [56]:
print(sum(arr[[i for i in range(len(arr)//2+1)], [i for i in range(len(arr)//2, -1, -1)]])+
sum(arr[[i for i in range(len(arr)//2, len(arr))],[i for i in range(len(arr)-1, len(arr)//2-1, -1)]])+
sum(arr[[i for i in range(1,len(arr)//2)],[i for i in range(len(arr)//2+1,len(arr)-1)]])+
sum(arr[[i for i in range(len(arr)//2+1,len(arr)-1)],[i for i in range(1,len(arr)//2)]]))

315


In [5]:
print(arr[[i for i in range(len(arr)//2, len(arr))],[i for i in range(len(arr)-1, len(arr)//2-1, -1)]],
arr[[i for i in range(len(arr)//2, len(arr))],[i for i in range(len(arr)-1, len(arr)//2-1, -1)]],
arr[[i for i in range(1, len(arr)//2)],
    [i for i in range(len(arr)//2+1, len(arr)-1)]],
arr[[i for i in range(len(arr)//2+1,len(arr)-1)],[i for i in range(1,len(arr)//2)]])

[21 26 35 41] [21 26 35 41] [21 34] [ 6 26]


# 28/09/22

In [6]:
import numpy as np

arr=np.arange(15).reshape(5,3)
print(arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [9]:
# deletion

print(np.delete(arr,0)) # array , index
print(np.delete(arr, [0,1,7])) # array, list of index

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 2  3  4  5  6  8  9 10 11 12 13 14]


In [11]:
print(np.delete(arr, [0],axis=0))
print(np.delete(arr, [0,1,3],axis=0))

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[ 6  7  8]
 [12 13 14]]


In [13]:
print(np.delete(arr, [0],axis=1))
print(np.delete(arr, [0,2],axis=1))

[[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]
 [13 14]]
[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]]


In [20]:
# unique method
arr=np.random.randint(2,10,(3,3))
print(arr)
print(np.unique(arr))
print(np.unique(arr,return_index=True)) # output: unique value, index of unique values

[[8 6 8]
 [2 4 8]
 [4 4 2]]
[2 4 6 8]
(array([2, 4, 6, 8]), array([3, 4, 1, 0]))


In [21]:
print(np.unique(arr,return_counts=True)) # output: unique values, count

(array([2, 4, 6, 8]), array([2, 3, 1, 3]))


In [24]:
arr=np.arange(9).reshape(3,3)
print(arr)
# repeate 
print(np.repeat(arr,2,axis=0))
print(np.repeat(arr,2,axis=1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [0 1 2]
 [3 4 5]
 [3 4 5]
 [6 7 8]
 [6 7 8]]
[[0 0 1 1 2 2]
 [3 3 4 4 5 5]
 [6 6 7 7 8 8]]


In [27]:
# cumulative sum
print(arr)
print(np.cumsum(arr))
print(np.cumsum(arr,axis=0))
print(np.cumsum(arr,axis=1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[ 0  1  3  6 10 15 21 28 36]
[[ 0  1  2]
 [ 3  5  7]
 [ 9 12 15]]
[[ 0  1  3]
 [ 3  7 12]
 [ 6 13 21]]


In [ ]:
# store array in mysql in table

## Pandas

In [ ]:
import pandas as pd
import numpy as np


**Continued on basics_4.ipynb**